SET SQLBLANKLINES ON
CREATE TABLE SUB_CALIFICACIONES 
(
  CALIDSECUENCIA NUMBER(10) NOT NULL 
, CALSUBASTA NUMBER(6) NOT NULL 
, CALUSUARIO VARCHAR2(15) NOT NULL 
, CALCALIFICACION NUMBER(1) NOT NULL 
, CALFECHA DATE NOT NULL 
, CALROL VARCHAR2(15) NOT NULL 
, CONSTRAINT SUB_CALIFICACIONES_PK PRIMARY KEY 
  (
    CALIDSECUENCIA 
  )
  ENABLE 
);

CREATE TABLE SUB_CIUDADES 
(
  CIUCODIGO VARCHAR2(3) NOT NULL 
, CIUDESCRIPCION VARCHAR2(100) NOT NULL 
, CIUESTADO VARCHAR2(3) NOT NULL 
, CIUPAIS VARCHAR2(3) NOT NULL 
, CONSTRAINT SUB_CIUDADES_PK PRIMARY KEY 
  (
    CIUCODIGO 
  , CIUPAIS 
  , CIUESTADO 
  )
  ENABLE 
);

CREATE TABLE SUB_COMUNICACIONES 
(
  COMIDSECUENCIA NUMBER(10) NOT NULL 
, COMUSUARIO VARCHAR2(15) NOT NULL 
, COMEMAIL VARCHAR2(20) NOT NULL 
, COMFECHAENVIO DATE NOT NULL 
, COMMENSAJE VARCHAR2(4000) NOT NULL 
, COMTIPOMENSAJE VARCHAR2(19) NOT NULL 
, COMSUBASTA NUMBER(10) NOT NULL 
, COMROL VARCHAR2(15) NOT NULL 
, CONSTRAINT SUB_COMUNICACIONES_PK PRIMARY KEY 
  (
    COMIDSECUENCIA 
  )
  ENABLE 
);

CREATE TABLE SUB_ESTADOS 
(
  ESTCODIGO VARCHAR2(3) NOT NULL 
, ESTDESCRIPCION VARCHAR2(100) NOT NULL 
, ESTPAIS VARCHAR2(3) NOT NULL 
, CONSTRAINT SUB_ESTADOS_PK PRIMARY KEY 
  (
    ESTCODIGO 
  , ESTPAIS 
  )
  ENABLE 
);

CREATE TABLE SUB_OFERTAS 
(
  OFECODIGO NUMBER(4) NOT NULL 
, OFESUBASTA NUMBER(6) NOT NULL 
, OFEFECHAHORAOFERTA TIMESTAMP(4) NOT NULL 
, OFEPRECIOPUJA NUMBER(12) NOT NULL 
, OFECOMPRADOR VARCHAR2(15) NOT NULL 
, CONSTRAINT SUB_OFERTAS_PK PRIMARY KEY 
  (
    OFECODIGO 
  , OFESUBASTA 
  )
  ENABLE 
);

CREATE TABLE SUB_PAGOS 
(
  PAGIDSECUENCIA NUMBER(10) NOT NULL 
, PAGSUBASTA NUMBER(10) NOT NULL 
, PAGESTADO VARCHAR2(10) NOT NULL 
, PAGVALORPAGO NUMBER(12) NOT NULL 
, PAGNROTARJETACREDITO VARCHAR2(50) NOT NULL 
, PAGFECHAVENCIMIENTOTARJETA DATE NOT NULL 
, PAGGASTOSENVIO NUMBER(12) NOT NULL 
, PAGVALORIMPUESTO NUMBER(12) NOT NULL 
, PAGVALORCOMISION NUMBER(12) NOT NULL 
, PAGNROFACTURA NUMBER(10) NOT NULL 
, PAGFECHAPAGO DATE NOT NULL 
, CONSTRAINT SUB_PAGOS_PK PRIMARY KEY 
  (
    PAGIDSECUENCIA 
  , PAGSUBASTA 
  )
  ENABLE 
);

CREATE TABLE SUB_PAISES 
(
  PAICODIGO VARCHAR2(3) NOT NULL 
, PAIDESCRIPCION VARCHAR2(100) NOT NULL 
, PAICONTINENTE VARCHAR2(20) NOT NULL 
, CONSTRAINT SUB_PAISES_PK PRIMARY KEY 
  (
    PAICODIGO 
  )
  ENABLE 
);

CREATE TABLE SUB_PRODUCTOS 
(
  PROCODIGO NUMBER(10) NOT NULL 
, PRODESCRIPCION VARCHAR2(500) NOT NULL 
, PROCONDICION VARCHAR2(20) NOT NULL 
, PROPESO NUMBER(6, 2) NOT NULL 
, PROGENERO VARCHAR2(9) NOT NULL 
, PROPRECIOBASE NUMBER(12) NOT NULL 
, PROIDVENDEDOR VARCHAR2(15) NOT NULL 
, PROTIEMPOENTREGA NUMBER(2) NOT NULL 
, PROCATEGORIA VARCHAR2(15) NOT NULL 
, PROCERTIFICADOGARANTIA VARCHAR2(2) NOT NULL 
, CONSTRAINT SUB_PRODUCTOS_PK PRIMARY KEY 
  (
    PROCODIGO 
  )
  ENABLE 
);

CREATE TABLE SUB_ROLES 
(
  ROLCODIGOROL VARCHAR2(15) NOT NULL 
, ROLDESCRIPCION VARCHAR2(20) NOT NULL 
, CONSTRAINT SUB_ROLES_PK PRIMARY KEY 
  (
    ROLCODIGOROL 
  )
  ENABLE 
);

CREATE TABLE SUB_SUBASTAS 
(
  SUBCODIGO NUMBER(10) NOT NULL 
, SUBPRODUCTO NUMBER(10) NOT NULL 
, SUBFECHAHORAINICIO TIMESTAMP(4) NOT NULL 
, SUBFECHAHORAFIN TIMESTAMP(4) NOT NULL 
, SUBESTADO VARCHAR2(12) NOT NULL 
, SUBGANADOR VARCHAR2(15) 
, SUBESPAGADA VARCHAR2(2) 
, USUCODIGOUSUARIO VARCHAR2(15) NOT NULL 
, CONSTRAINT SUB_SUBASTAS_PK PRIMARY KEY 
  (
    SUBCODIGO 
  )
  ENABLE 
);

CREATE TABLE SUB_USUARIOS 
(
  USUCODIGOUSUARIO VARCHAR2(15) NOT NULL 
, USUNOMBRE VARCHAR2(50) NOT NULL 
, USUAPELLIDOS VARCHAR2(50) NOT NULL 
, USULOGGIN VARCHAR2(50) NOT NULL 
, USUPASSWORD VARCHAR2(15) NOT NULL 
, USUSEXO VARCHAR2(1) NOT NULL 
, USUDIRECCIONENVIO VARCHAR2(200) NOT NULL 
, USUTELEFONO1 VARCHAR2(15) NOT NULL 
, USUTELEFONO2 VARCHAR2(15) 
, USUFECHANACIMIENTO DATE NOT NULL 
, USUFECHAINGRESO DATE NOT NULL 
, USUCODPOSTAL VARCHAR2(10) NOT NULL 
, USUPAIS VARCHAR2(3) NOT NULL 
, USUESTADO VARCHAR2(3) NOT NULL 
, USUCIUDAD VARCHAR2(3) NOT NULL 
, USUEMAIL VARCHAR2(100) NOT NULL 
, USUROL VARCHAR2(15) NOT NULL 
, USUNICKNAME VARCHAR2(50) 
, USUREPUTACIONCOMPRADOR VARCHAR2(9) 
, USUREPUTACIONVENDEDOR VARCHAR2(9) 
, USUESTADOUSUARIO VARCHAR2(10) NOT NULL 
, USUINFORMARSUBASTA VARCHAR2(2) NOT NULL 
, CONSTRAINT SUB_USUARIOS_PK PRIMARY KEY 
  (
    USUCODIGOUSUARIO 
  )
  ENABLE 
);

ALTER TABLE SUB_CALIFICACIONES
ADD CONSTRAINT FK_CALIFICACIONES_ROL FOREIGN KEY
(
  CALROL 
)
REFERENCES SUB_ROLES
(
  ROLCODIGOROL 
)
ENABLE;

ALTER TABLE SUB_CALIFICACIONES
ADD CONSTRAINT FK_CALIFICACIONES_SUBASTAS FOREIGN KEY
(
  CALSUBASTA 
)
REFERENCES SUB_SUBASTAS
(
  SUBCODIGO 
)
ENABLE;

ALTER TABLE SUB_CALIFICACIONES
ADD CONSTRAINT FK_CALIFICACIONES_USUARIOS FOREIGN KEY
(
  CALUSUARIO 
)
REFERENCES SUB_USUARIOS
(
  USUCODIGOUSUARIO 
)
ENABLE;

ALTER TABLE SUB_CIUDADES
ADD CONSTRAINT FK_CIUDADES_ESTADOS FOREIGN KEY
(
  CIUESTADO 
)
REFERENCES SUB_ESTADOS
(
  ESTCODIGO 
, ESTPAIS 
)
ENABLE;

ALTER TABLE SUB_CIUDADES
ADD CONSTRAINT FK_CIUDADES_PAISES FOREIGN KEY
(
  CIUPAIS 
)
REFERENCES SUB_PAISES
(
  PAICODIGO 
)
ENABLE;

ALTER TABLE SUB_COMUNICACIONES
ADD CONSTRAINT FK_COMUNICACIONES_ROLES FOREIGN KEY
(
  COMROL 
)
REFERENCES SUB_ROLES
(
  ROLCODIGOROL 
)
ENABLE;

ALTER TABLE SUB_COMUNICACIONES
ADD CONSTRAINT FK_COMUNICACIONES_SUBASTAS FOREIGN KEY
(
  COMSUBASTA 
)
REFERENCES SUB_SUBASTAS
(
  SUBCODIGO 
)
ENABLE;

ALTER TABLE SUB_COMUNICACIONES
ADD CONSTRAINT FK_COMUNICACIONES_USUARIOS FOREIGN KEY
(
  COMUSUARIO 
)
REFERENCES SUB_USUARIOS
(
  USUCODIGOUSUARIO 
)
ENABLE;

ALTER TABLE SUB_ESTADOS
ADD CONSTRAINT FK_ESTADOS_PAISES FOREIGN KEY
(
  ESTPAIS 
)
REFERENCES SUB_PAISES
(
  PAICODIGO 
)
ENABLE;

ALTER TABLE SUB_OFERTAS
ADD CONSTRAINT FK_OFERTAS_SUBASTAS FOREIGN KEY
(
  OFESUBASTA 
)
REFERENCES SUB_SUBASTAS
(
  SUBCODIGO 
)
ENABLE;

ALTER TABLE SUB_OFERTAS
ADD CONSTRAINT FK_OFERTAS_USUARIOS FOREIGN KEY
(
  OFECOMPRADOR 
)
REFERENCES SUB_USUARIOS
(
  USUCODIGOUSUARIO 
)
ENABLE;

ALTER TABLE SUB_PAGOS
ADD CONSTRAINT FK_PAGOS_SUBASTAS FOREIGN KEY
(
  PAGSUBASTA 
)
REFERENCES SUB_SUBASTAS
(
  SUBCODIGO 
)
ENABLE;

ALTER TABLE SUB_PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOS_USUARIOS FOREIGN KEY
(
  PROIDVENDEDOR 
)
REFERENCES SUB_USUARIOS
(
  USUCODIGOUSUARIO 
)
ENABLE;

ALTER TABLE SUB_SUBASTAS
ADD CONSTRAINT FK_SUBASTAS_PRODUCTOS FOREIGN KEY
(
  SUBPRODUCTO 
)
REFERENCES SUB_PRODUCTOS
(
  PROCODIGO 
)
ENABLE;

ALTER TABLE SUB_SUBASTAS
ADD CONSTRAINT FK_SUBASTAS_USUARIOS FOREIGN KEY
(
  SUBGANADOR 
)
REFERENCES SUB_USUARIOS
(
  USUCODIGOUSUARIO 
)
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT FK_USUARIOS_CIUDAD FOREIGN KEY
(
  USUCIUDAD 
, USUPAIS 
, USUESTADO 
)
REFERENCES SUB_CIUDADES
(
  CIUCODIGO 
, CIUPAIS 
, CIUESTADO 
)
ENABLE;

ALTER TABLE SUB_CALIFICACIONES
ADD CONSTRAINT SUB_CALIFICACIONES_CAL CHECK 
(CALCALIFICACION in (1, -1))
ENABLE;

ALTER TABLE SUB_COMUNICACIONES
ADD CONSTRAINT SUB_COMUNICACIONES_TIPOMENSAJE CHECK 
(COMTIPOMENSAJE in ('Tramitar pago', 'Aceptacion oferta', 'Cierre Subasta', 'Cancelacion Subasta', 'Rechazo Pago', 'Aceptacion Pago', 'Bienvenida', 'Incumplimiento', 'Sancion'))
ENABLE;

ALTER TABLE SUB_PAGOS
ADD CONSTRAINT SUB_PAGOS_ESTADO CHECK 
(PAGESTADO in ('Aceptado', 'Rechazado', 'En tramite'))
ENABLE;

ALTER TABLE SUB_PAISES
ADD CONSTRAINT SUB_PAISES_CONTINENTE CHECK 
(PAICONTINENTE in ('America', 'Africa', 'Europa', 'Asia', 'Oceania'))
ENABLE;

ALTER TABLE SUB_PRODUCTOS
ADD CONSTRAINT SUB_PRODUCTOS_CERTGARANTIA CHECK 
(PROCERTIFICADOGARANTIA in ('Si', 'No'))
ENABLE;

ALTER TABLE SUB_PRODUCTOS
ADD CONSTRAINT SUB_PRODUCTOS_DIASGARANTIA CHECK 
(PRODIASGARANTIA >= 0)
ENABLE;

ALTER TABLE SUB_PRODUCTOS
ADD CONSTRAINT SUB_PRODUCTOS_PROGENERO CHECK 
(progenero in ('Masculino', 'Femenino', 'Unisex'))
ENABLE;

ALTER TABLE SUB_PRODUCTOS
ADD CONSTRAINT SUB_PRODUCTOS_UDPESO CHECK 
(prounidadpeso in ('Kilo', 'Litros', 'Gramos', 'Mililitros'))
ENABLE;

ALTER TABLE SUB_ROLES
ADD CONSTRAINT SUB_ROLES_CODROL CHECK 
(ROLCODIGOROL in ('Comprador', 'Vendedor', 'Ambos'))
ENABLE;

ALTER TABLE SUB_SUBASTAS
ADD CONSTRAINT SUB_SUBASTAS_SUBESPAGADA CHECK 
(subespagada in ('Si', 'No'))
ENABLE;

ALTER TABLE SUB_SUBASTAS
ADD CONSTRAINT SUB_SUBASTAS_SUBESTADO CHECK 
(subestado in ('Creada','En Ejecucion', 'Adjudicada', 'Cerrada', 'Cancelada'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_ESTADOUSUARIO CHECK 
(USUESTADOUSUARIO in ('Activo', 'Suspendido', 'Inactivo'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_FORMARSUBASTA CHECK 
(USUESTADOUSUARIO in ('Si', 'No'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_REPCOMPRADOR CHECK 
(USUREPUTACIONCOMPRADOR in ('Excelente', 'Buena', 'Regular', 'Mala'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_REPVENDEDOR CHECK 
(USUREPUTACIONVENDEDOR in ('Excelente', 'Buena', 'Regular', 'Mala'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_ROL CHECK 
(USUROL in ('Comprador', 'Vendedor', 'Ambos'))
ENABLE;

ALTER TABLE SUB_USUARIOS
ADD CONSTRAINT SUB_USUARIOS_SEXO CHECK 
(USUSEXO in ('M', 'F'))
ENABLE;

COMMENT ON COLUMN SUB_CALIFICACIONES.CALIDSECUENCIA IS 'Permite identificar cada calificación otorgada';

COMMENT ON COLUMN SUB_CALIFICACIONES.CALSUBASTA IS 'Identificación o número de la subasta';

COMMENT ON COLUMN SUB_CALIFICACIONES.CALUSUARIO IS 'Identificación del usuario';

COMMENT ON COLUMN SUB_CALIFICACIONES.CALCALIFICACION IS 'Grado de satisfacción con la compra-venta del producto';

COMMENT ON COLUMN SUB_CALIFICACIONES.CALFECHA IS 'Fecha en la que se realiza la calificación';

COMMENT ON COLUMN SUB_CALIFICACIONES.CALROL IS 'Rol (comprador–vendedor) que tiene cada participante en la subasta';

COMMENT ON COLUMN SUB_CIUDADES.CIUCODIGO IS 'Código numérico que identifica a una ciudad';

COMMENT ON COLUMN SUB_CIUDADES.CIUDESCRIPCION IS 'En este se especifica el nombre de la ciudad donde se ubica el usuario';

COMMENT ON COLUMN SUB_CIUDADES.CIUESTADO IS 'Identificación del estado(ciudad)';

COMMENT ON COLUMN SUB_CIUDADES.CIUPAIS IS 'Identificación del país';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMIDSECUENCIA IS 'Identificación de cada comunicación enviada';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMUSUARIO IS 'Identificación del usuario';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMEMAIL IS 'Contiene la dirección de correo electrónico del empleado.';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMFECHAENVIO IS 'Fecha en la que se envía esa comunicación';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMMENSAJE IS 'Contenido del mensaje';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMTIPOMENSAJE IS 'Clasificación del mensaje';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMSUBASTA IS 'Identificación de la subasta por la cual se genera una comunicación';

COMMENT ON COLUMN SUB_COMUNICACIONES.COMROL IS 'Identificación del rol de un usuario';

COMMENT ON COLUMN SUB_ESTADOS.ESTCODIGO IS 'Identifica el código de la ciudad donde se ubica el usuario';

COMMENT ON COLUMN SUB_ESTADOS.ESTDESCRIPCION IS 'En este se especifica el nombre de la ciudad de ubicación del usuario';

COMMENT ON COLUMN SUB_ESTADOS.ESTPAIS IS 'Número que identifica el país donde se ubica el usuario';

COMMENT ON COLUMN SUB_OFERTAS.OFECODIGO IS 'Código que identifica a cada oferta';

COMMENT ON COLUMN SUB_OFERTAS.OFESUBASTA IS 'Identificación de una subasta';

COMMENT ON COLUMN SUB_OFERTAS.OFEFECHAHORAOFERTA IS 'Registro de la fecha, hora de una oferta';

COMMENT ON COLUMN SUB_OFERTAS.OFEPRECIOPUJA IS 'Valor económico por  el cual se puja a una oferta';

COMMENT ON COLUMN SUB_OFERTAS.OFECOMPRADOR IS 'Contiene la identificación de cada usuario comprador';

COMMENT ON COLUMN SUB_PAGOS.PAGIDSECUENCIA IS 'Nos permite asignar una identificación única de un pago que se realiza a una subasta.';

COMMENT ON COLUMN SUB_PAGOS.PAGSUBASTA IS 'Nos permite asignar una identificación única a cada subasta.';

COMMENT ON COLUMN SUB_PAGOS.PAGESTADO IS 'Permite identificar si un pago está en el estado pagado, en proceso o en difícil cobro.';

COMMENT ON COLUMN SUB_PAGOS.PAGVALORPAGO IS 'Contiene el valor de un pago realizado';

COMMENT ON COLUMN SUB_PAGOS.PAGNROTARJETACREDITO IS 'Contiene el número con el cual se identifica la tarjeta de crédito con la cual se efectuará un pago';

COMMENT ON COLUMN SUB_PAGOS.PAGFECHAVENCIMIENTOTARJETA IS 'Contiene la fecha completa en la cual vence la tarjeta de crédito con la cual se efectúa un pago';

COMMENT ON COLUMN SUB_PAGOS.PAGGASTOSENVIO IS 'Permite identificar el valor de los gastos de envío de un producto subastado';

COMMENT ON COLUMN SUB_PAGOS.PAGVALORIMPUESTO IS 'Contiene el valor del impuesto a pagar por cada producto subastado.';

COMMENT ON COLUMN SUB_PAGOS.PAGVALORCOMISION IS 'Contiene el valor establecido por cada subasta como comisión para el sitio';

COMMENT ON COLUMN SUB_PAGOS.PAGNROFACTURA IS 'Permite identificar el número único de cada factura entregada a un ganador de una subasta';

COMMENT ON COLUMN SUB_PAGOS.PAGFECHAPAGO IS 'Permite identificar la fecha en la cual se ha realizado el pago de una factura y que corresponde a una subasta';

COMMENT ON COLUMN SUB_PAISES.PAICODIGO IS 'Identifica el código del país donde se ubica el usuario';

COMMENT ON COLUMN SUB_PAISES.PAIDESCRIPCION IS 'Nombre del país';

COMMENT ON COLUMN SUB_PAISES.PAICONTINENTE IS 'Nombre del continente al que pertenece el país de origen del cliente';

COMMENT ON COLUMN SUB_PRODUCTOS.PROCODIGO IS 'Nos permite asignar una identificación única a cada producto.';

COMMENT ON COLUMN SUB_PRODUCTOS.PRODESCRIPCION IS 'Permite establecer las características que componen un producto';

COMMENT ON COLUMN SUB_PRODUCTOS.PROCONDICION IS 'Permite clarificar en qué condiciones se encuentra el producto';

COMMENT ON COLUMN SUB_PRODUCTOS.PROPESO IS 'Identifica el peso que tiene cada producto a ser subastado';

COMMENT ON COLUMN SUB_PRODUCTOS.PROGENERO IS 'Permite establecer el género que posee cada producto';

COMMENT ON COLUMN SUB_PRODUCTOS.PROPRECIOBASE IS 'Nos permite asignar un precio con el cual iniciará la subasta un producto.';

COMMENT ON COLUMN SUB_PRODUCTOS.PROIDVENDEDOR IS 'Permite identificar un vendedor relacionado a un producto';

COMMENT ON COLUMN SUB_PRODUCTOS.PROTIEMPOENTREGA IS 'Permite asignar un tiempo límite en el cual se deberá entregar el producto subastado';

COMMENT ON COLUMN SUB_PRODUCTOS.PROCATEGORIA IS 'Asignar representados en días la garantía que se le da al producto a subastar';

COMMENT ON COLUMN SUB_PRODUCTOS.PROCERTIFICADOGARANTIA IS 'Permite asignar la identificación de un certificado de garantía de un producto a subastar';

COMMENT ON COLUMN SUB_ROLES.ROLCODIGOROL IS 'Código que identifica el rol tomado por un usuario.';

COMMENT ON COLUMN SUB_ROLES.ROLDESCRIPCION IS 'Describe el rol que puede tomar un usuario';

COMMENT ON COLUMN SUB_SUBASTAS.SUBCODIGO IS 'Identificamos a través de un número, una subasta
';

COMMENT ON COLUMN SUB_SUBASTAS.SUBPRODUCTO IS 'Permite identificar a través de un número un producto que ha sido subastado o se encuentra en subasta';

COMMENT ON COLUMN SUB_SUBASTAS.SUBFECHAHORAINICIO IS 'Contiene el registro de la fecha, hora en que se inicia una subasta';

COMMENT ON COLUMN SUB_SUBASTAS.SUBFECHAHORAFIN IS 'Contiene el registro de la fecha, hora en que finaliza una subasta';

COMMENT ON COLUMN SUB_SUBASTAS.SUBESTADO IS 'Permite identificar en qué estado se encuentra una subasta en un determinado tiempo';

COMMENT ON COLUMN SUB_SUBASTAS.SUBGANADOR IS 'Permite identificar  al ganador (usuario comprador) de la subasta';

COMMENT ON COLUMN SUB_SUBASTAS.SUBESPAGADA IS 'Contiene el registro de si la subasta fue o no pagada';

COMMENT ON COLUMN SUB_USUARIOS.USUCODIGOUSUARIO IS 'Código que identifica de manera única dentro del sitio a un usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUNOMBRE IS 'Nombre que identifica a un usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUAPELLIDOS IS 'Apellidos que identifican a un usuario';

COMMENT ON COLUMN SUB_USUARIOS.USULOGGIN IS 'log con el cual el usuario desea acceder al servidor web';

COMMENT ON COLUMN SUB_USUARIOS.USUPASSWORD IS 'Clave con la cual desea acceder al sitio';

COMMENT ON COLUMN SUB_USUARIOS.USUSEXO IS 'Identificación genética de un usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUDIRECCIONENVIO IS 'Dirección de ubicación del usuario para realizarle posibles envíos de correo';

COMMENT ON COLUMN SUB_USUARIOS.USUTELEFONO1 IS 'Contiene el número de teléfono en el cual se puede contactar al usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUTELEFONO2 IS 'Contiene el número de teléfono adicional en el cual se puede contactar al usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUFECHANACIMIENTO IS 'Fecha de nacimiento del usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUFECHAINGRESO IS 'Fecha en la cual se registro en el sitio';

COMMENT ON COLUMN SUB_USUARIOS.USUCODPOSTAL IS 'Código postal del lugar de residencia del usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUPAIS IS 'Identificación del país de donde reside el usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUESTADO IS 'En este campo se identifica con un número determinado el estado donde se ubica el usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUCIUDAD IS 'Permite reconocer identificando con un número la ciudad donde ubicamos al usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUEMAIL IS 'Permite la identificación del rol que toma un usuario en una subasta.';

COMMENT ON COLUMN SUB_USUARIOS.USUROL IS 'Permite la identificación de un usuario cuando participa en una subasta';

COMMENT ON COLUMN SUB_USUARIOS.USUNICKNAME IS 'Contiene información del cumplimiento de un usuario comprador a los compromisos adquiridos en una subasta.  Es útil para determinar la confiabilidad con el usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUREPUTACIONCOMPRADOR IS 'Contiene información del cumplimiento de un usuario vendedor a los compromisos adquiridos en una subasta.  Es útil para determinar la confiabilidad con el usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUREPUTACIONVENDEDOR IS 'Contiene información del cumplimiento de un usuario vendedor a los compromisos adquiridos en una subasta.  Es útil para determinar la confiabilidad con el usuario';

COMMENT ON COLUMN SUB_USUARIOS.USUESTADOUSUARIO IS 'Determina el estado del usuario, es útil para determinar si puede participar en una subastas(comprar, vender).';

COMMENT ON COLUMN SUB_USUARIOS.USUINFORMARSUBASTA IS 'Si el usuario acepta el envío de  anuncios de nuevas subatas.';
